# Generated by Django 5.2.3 on 2025-07-05 18:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_minutes', models.PositiveIntegerField(default=120)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chapter_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField()),
                ('topic_count', models.PositiveIntegerField(default=1)),
                ('recommended_time', models.FloatField(help_text='Recommended study time in hours')),
                ('importance', models.JSONField(default={'engineering': 0, 'hsc': 0, 'medical': 0, 'varsity': 0})),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='syllebus.subject')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('subject', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(help_text='Sequence in chapter')),
                ('description', models.TextField()),
                ('resource_link', models.TextField(blank=True)),
                ('importance', models.JSONField(default={'engineering': 10, 'hsc': 10, 'medical': 10, 'varsity': 10})),
                ('time_percent', models.PositiveIntegerField(default=10, help_text='Time percentage for this topic (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllebus.chapter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allocated_minutes', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='syllebus.studyroutine')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.topic')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('hsc', 'HSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('varsity', 'Varsity')], default='hsc', max_length=20)),
                ('show_on_leaderboard', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('overall_progress_cache', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='studyroutine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='syllebus.userprofile'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.userprofile')),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('C', 'Completed'), ('R', 'Needs Revision')], default='NS', max_length=2)),
                ('skip', models.BooleanField(default=False)),
                ('personal_note', models.TextField(blank=True, null=True)),
                ('time_given', models.FloatField(help_text='Time given in hours')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllebus.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='syllebus_us_status_c00c4a_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
