# Generated by Django 5.2.3 on 2025-07-06 06:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chapter_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField()),
                ('topic_count', models.PositiveIntegerField(default=1)),
                ('recommended_time', models.FloatField(help_text='Recommended study time in hours')),
                ('importance', models.JSONField(default=dict)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='syllabus.subject')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('subject', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(help_text='Sequence in chapter')),
                ('description', models.TextField()),
                ('resource_link', models.TextField(blank=True)),
                ('importance', models.JSONField(default=dict)),
                ('time_percent', models.PositiveIntegerField(default=10, help_text='Time percentage for this topic (0-100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.chapter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
