# Generated by Django 5.2.3 on 2025-07-06 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('hsc', 'HSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('varsity', 'Varsity')], default='hsc', max_length=20)),
                ('show_on_leaderboard', models.BooleanField(default=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('overall_progress_cache', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('C', 'Completed'), ('R', 'Needs Revision')], default='NS', max_length=2)),
                ('skip', models.BooleanField(default=False)),
                ('personal_note', models.TextField(blank=True, null=True)),
                ('time_given', models.FloatField(help_text='Time given in hours')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='syllabus.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='users_userp_status_616575_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
