# Generated by Django 5.2.3 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_college_alter_userprogress_p_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hscyear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
