# Generated by Django 5.2.3 on 2025-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_hscyear_alter_userprofile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hscyear',
            field=models.PositiveIntegerField(blank=True, choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], null=True),
        ),
    ]
