# Generated by Django 5.2.3 on 2025-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_college_alter_userprofile_hscyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hscyear',
            field=models.PositiveIntegerField(blank=True, choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028')], null=True),
        ),
    ]
