# Generated by Django 5.2.3 on 2025-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroutine',
            name='plan_data',
            field=models.JSONField(default=dict),
        ),
    ]
