# Generated by Django 5.2.3 on 2025-07-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_studyroutine_plan_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlannedTask',
        ),
    ]
